image:
  registry: ghcr.io/dmxmss
  tag: latest
  pullPolicy: IfNotPresent

publicBaseUrl: http://short.local
redirectPublicUrl: http://redirect.local

imagePullSecrets:
  - name: ghcr-secret

postgresql:
  image: postgres:16-alpine
  auth:
    username: shortener
    password: shortener
    database: shortener
  storage: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

redis:
  image: redis:7-alpine
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi

nats:
  enabled: false
  image: nats:2.10-alpine

shortenerApi:
  replicas: 1
  service:
    enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 128Mi

redirectService:
  replicas: 2
  service:
    enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 128Mi

frontend:
  replicas: 1
  service:
    enabled: true
  apiBaseUrl: ""
  apiUpstream: ""
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

ingressRoute:
  enabled: false

  entryPoints:
    - web

  tls:
    enabled: false

ingress:
  enabled: true
  clusterIssuer: letsencrypt
  ingressClassName: traefik
  host: semgateam.ru
  tls:
    enabled: true
    secretName: tls-semgateam-ru

  items:
    - name: shortener-api-ingress
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-api-strip-prefix@kubernetescrd
      path: /api  
      service:
        name: url-shortener-url-shortener-shortener-api
        port: 80

    - name: redirect-service-ingress
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-strip-prefix@kubernetescrd
      path: /redirect
      service:
        name: url-shortener-url-shortener-redirect-service
        port: 80

    - name: frontend-ingress
      path: /
      service:
        name: url-shortener-url-shortener-frontend
        port: 80

