deployment:
  replicas: 1

service:
  spec:
    type: ClusterIP

ports:
  web:
    port: 8000
    exposedPort: 80
    hostPort: 80

providers:
  kubernetesCRD:
    enabled: true

  kubernetesIngress:
    enabled: true

ingressRoute:
  dashboard:
    enabled: true

logs:
  general:
    level: INFO

additionalArguments:
  - "--api.insecure=true"
