apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.fullname" . }}-frontend-config
data:
  FRONTEND_API_UPSTREAM: {{ default (printf "http://%s-shortener-api" (include "url-shortener.fullname" .)) .Values.frontend.apiUpstream | quote }}
  config.js: |-
    window.__URL_SHORTENER_CONFIG__ = {
      API_BASE_URL: {{ .Values.frontend.apiBaseUrl | quote }}
    };
