apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.fullname" . }}-secret
type: Opaque
stringData:
  DATABASE_URL: postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "url-shortener.fullname" . }}-postgres:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable

