{{- if .Values.shortenerApi.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}-shortener-api
  labels:
    app.kubernetes.io/component: shortener-api
{{- if .Values.shortenerApi.service.labels }}
{{- toYaml .Values.shortenerApi.service.labels | nindent 4 }}
{{- end }}
spec:
  selector:
    app.kubernetes.io/component: shortener-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
{{- end }}
---
{{- if .Values.redirectService.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}-redirect-service
  labels:
    app.kubernetes.io/component: redirect-service
{{- if .Values.redirectService.service.labels }}
{{- toYaml .Values.redirectService.service.labels | nindent 4}}
{{- end }}
spec:
  selector:
    app.kubernetes.io/component: redirect-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
{{- end }}
---
{{- if .Values.redirectService.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
{{- if .Values.frontend.service.labels }}
{{- toYaml .Values.frontend.service.labels | nindent 4}}
{{- end }}
spec:
  selector:
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}
