apiVersion: v1
kind: Service
metadata:
  name: shortener-api
  namespace: url-shortener
spec:
  selector:
    app: shortener-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-api
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener-api
  template:
    metadata:
      labels:
        app: shortener-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: shortener-api
          image: registry.gitlab.com/dmxmss-group/dmxmss-project/shortener-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: url-shortener-config
            - secretRef:
                name: url-shortener-secret
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi

